server:
  port: 8888
spring:
  application:
    name: clientServer
  cloud:
    config:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    active: jdbc
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      post:
        enabled: true
    refresh:
      enabled: true
